### ISSUE TITLE
bitFlyer_要望

### ISSUE THREAD

**Issue by yukifujihira** [bitbankinc/uniform_cryptoasset_trade_history_csv_ja#24]
■現物
＜取引年月日＞
・yyyy/mm/dd hh:mm:ssの形式に変更希望
・暗号資産、法定通貨の入出金の場合はシステム登録日を記載とありますが、「システム登録日」の定義を確認したいです。当社では、当社システムに入った日時ではなく、顧客の残高を変動させた日時である「残高変動日時」を抽出しています。

＜取引種別＞
8.『証拠金預入』「証拠金口座への法定通貨・暗号資産の移動」として定義変更希望
9.『証拠金引出』「証拠金口座からの法定通貨・暗号資産の移動」として定義の変更希望
10.『受取』事業者からの付与。備考にハードフォークやステーキング等の記載をしてほしいです。
11.『ハードフォーク』カラム事態を削除し、他社が行っているステーキングサービス等と一緒に『受取』にマージし、備考にてハードフォークの旨を記載するのはどうでしょうか。

＜増加通貨名＞
・カラム名変更希望「通貨 1 」
・通貨ペア順で記載したいです。

＜増加数量＞
・カラム名変更希望「通貨 1 数量」
・増減については＋ー符号を使いし表現したいです。

＜減少通貨名＞
・カラム名変更希望「通貨 2 」
・通貨ペア順で記載したいです。

＜減少数量＞
・カラム名変更希望「通貨 2 数量」
・増減については＋ー符号を使いし表現したいです。

＜単価＞
・カラム名変更希望「通貨 1 の対円レート」
・「取引種別が「入金」「出金」「手数料」以外の場合、通貨1 の対円レートを記載」として定義の変更希望。

＜備考＞
・取引種別が『その他』『受取』に含まれるものの取引種別を出力したいです。例えば、当社では、
「bitWire SHOP（ビットコイン決済）の支払い」「定期預入」「定期払戻」「手数料返金」「受取」「ショップ受取」「ハードフォーク」等が該当します。

＜追加希望カラム＞
・『注文 ID』抽出定義は、取引種別全て、当社管理の注文IDとなります。

■デリバティブ
＜取引年月日＞
・yyyy/mm/dd hh:mm:ssの形式に変更希望
・暗号資産、法定通貨の入出金の場合はシステム登録日を記載とありますが、「システム登録日」の定義を確認したいです。当社では、当社システムに入った日時ではなく、顧客の残高を変動させた日時である「残高変動日時」を抽出しています。

＜取引種別＞
**※ 前提として、当社のデリバティブ取引は、販売所形式ではなく板形式であるため、注文は必ずしも約定しません。**
1.『新規』 上記の理由から項目の削除を希望します。
3.『証拠金受入』名称変更 「証拠金預入」、定義変更希望「現物口座から証拠金口座への法定通貨・暗号資産の移動」当社は証拠金として暗号資産の預入が可能なため。
4.『証拠金引出』、定義変更希望「証拠金口座からの法定通貨・暗号資産の移動」

・追加項目希望
『充当』当社のFXと先物取引では、証拠金を日本円だけでなく、ビットコインで預け入れることができます。差金決済では日本円の証拠金のみが増減し、日本円の証拠金がマイナスになることがあるため、BTCで預け入れた証拠金を減らすことで、このマイナス分を解消する操作のことを「充当」と定義しています。

『その他』当社の場合、SFD、現引、現渡などが含まれ、備考にて詳細を記載したいです。

＜通貨ペア＞
・定義の変更希望です。当社では以下で定義しています。
ー取引がFXの場合、『FX_シンボル_（基軸）シンボル』で記載
ー取引が先物の場合、『BTCJPY満期日』(ddMMMyyyy) で記載

＜入金・出金＞
・『取引種別』の『証拠金受入』『証拠金引出』と重複しているためカラム自体の削除希望です。

＜レバレッジ手数料＞
・カラム名変更希望「スワップポイント」
・当社ではスワップポイントとして抽出しています。定義：建玉に対して発生したスワップポイントをJPYで記載

＜約定番号＞
・当社では現状『注文 ID』『取引ID』の2つがあるためそれを残す必要があり、当社管理の注文・取引IDを記載したいです。

**Comment by naoji** [comment]
@yukifujihira 
ありがとうございます！
お手数ですが、カラムや取引種別毎にコメント頂けますでしょうか。
他のIssueをご参考にしていただければと思います。
